import numpy as np
import pandas as pd
import torch
from torch.utils import data
import json

from sklearn.preprocessing import OneHotEncoder

from subword_nmt.apply_bpe import BPE
import codecs

vocab_path = './ESPF/protein_codes_uniprot.txt'
bpe_codes_protein = codecs.open(vocab_path)
pbpe = BPE(bpe_codes_protein, merges=-1, separator='')
sub_csv = pd.read_csv('./ESPF/subword_units_map_uniprot.csv')

idx2word_p = sub_csv['index'].values
words2idx_p = dict(zip(idx2word_p, range(0, len(idx2word_p))))

vocab_path = './ESPF/drug_codes_chembl.txt'
bpe_codes_drug = codecs.open(vocab_path)
dbpe = BPE(bpe_codes_drug, merges=-1, separator='')
sub_csv = pd.read_csv('./ESPF/subword_units_map_chembl.csv')

idx2word_d = sub_csv['index'].values
words2idx_d = dict(zip(idx2word_d, range(0, len(idx2word_d))))

max_d = 205
max_p = 545
 

def protein2emb_encoder(x):
    max_p = 545
    t1 = pbpe.process_line(x).split()  # split
    try:
        i1 = np.asarray([words2idx_p[i] for i in t1])  # index
    except:
        i1 = np.array([0])
        #print(x)

    l = len(i1)
   
    if l < max_p:
        i = np.pad(i1, (0, max_p - l), 'constant', constant_values = 0)
        input_mask = ([1] * l) + ([0] * (max_p - l))
    else:
        i = i1[:max_p]
        input_mask = [1] * max_p
        
    return i, np.asarray(input_mask)

def drug2emb_encoder(x):
    max_d = 50
    #max_d = 100
    t1 = dbpe.process_line(x).split()  # split
    try:
        i1 = np.asarray([words2idx_d[i] for i in t1])  # index
    except:
        i1 = np.array([0])
        #print(x)
    
    l = len(i1)

    if l < max_d:
        i = np.pad(i1, (0, max_d - l), 'constant', constant_values = 0)
        input_mask = ([1] * l) + ([0] * (max_d - l))

    else:
        i = i1[:max_d]
        input_mask = [1] * max_d

    return i, np.asarray(input_mask)


class BIN_Data_Encoder(data.Dataset):

    def __init__(self, list_IDs, labels, df_dti, test=False):
        'Initialization'
        self.labels = labels
        self.list_IDs = list_IDs
        self.df = df_dti
        self.test = test
    def __len__(self):
        'Denotes the total number of samples'
        return len(self.list_IDs)

    def __getitem__(self, index):
        'Generates one sample of data'
        # Select sample
        # Load data and get label
        index = self.list_IDs[index]
        #d = self.df.iloc[index]['DrugBank ID']
        d = self.df.iloc[index]['SMILES']
        p = self.df.iloc[index]['Target Sequence']
        if self.test:
            p = p 

            # uncomment percent delete of binding-site based on DiffDock generated 3D complex
            # p = get_modified_seq(p,d)

            # uncomment percent delete of binding-site based on AlphaFold3 generated 3D complex
            # p = get_modified_seq_alpha(p,d)

            # uncomment percent delete of protein sequence from 3 prime end
            # p = get_3_prime(p)


        #d_v = drug2single_vector(d)
        d_v, input_mask_d = drug2emb_encoder(d)
        p_v, input_mask_p = protein2emb_encoder(p)
        
        #print(d_v.shape)
        #print(input_mask_d.shape)
        #print(p_v.shape)
        #print(input_mask_p.shape)
        y = int(self.labels[index])
        return d_v, p_v, input_mask_d, input_mask_p, y

import hashlib
def generate_hashid(input_string):
    # Create a hash object using SHA-256
    hash_object = hashlib.sha256(input_string.encode())
    # Get the hexadecimal digest of the hash
    hex_digest = hash_object.hexdigest()
    # Return the first 4 characters of the hash
    return hex_digest[:10]
import MDAnalysis as mda, os
three_to_one = {
    "ALA": "A", "ARG": "R", "ASN": "N", "ASP": "D", "CYS": "C",
    "GLU": "E", "GLN": "Q", "GLY": "G", "HIS": "H", "ILE": "I",
    "LEU": "L", "LYS": "K", "MET": "M", "PHE": "F", "PRO": "P",
    "SER": "S", "THR": "T", "TRP": "W", "TYR": "Y", "VAL": "V"
}


def get_3_prime(seq):
    n = len(seq)
    percent = .1
    return seq[:int(n*percent)]


def get_modified_seq(seq,lig, cutoff_distance = 4.0):

    # hash = f"{generate_hashid(seq)}_{generate_hashid(lig)}"
    # path = f"../DTIVAR/datasets/bindingDB/diffdock_custom_test/{hash}/{hash}_complex.pdb"

    # path = * provide path to the 3D complex for $seq$ and $lig$ generated by DiffDock *

    if not os.path.isfile(path):
        print("3D complex not found for ", hash)
        return seq
    print("Found alpha MOD")
    u = mda.Universe(path)
    ligand = u.select_atoms("resname UNL")
    binding_site_residues = u.select_atoms(f"protein and around {cutoff_distance} group ligand", ligand=ligand)
    residues = {(res.resname, res.resid) for res in binding_site_residues.residues}
    residues = sorted(residues, key=lambda x:x[1])
    ress = "".join([three_to_one[x[0]] for x in residues])
    indices = [y-1 for x,y in residues]

    # seq2 = seq[:indices[0]] + seq[indices[-1]:]
    # seq2 = "".join([seq[i] for i in range(len(seq)) if i not in indices])

    percentage = 1.0
    k = int(((indices[-1]-indices[0])*percentage)//2)

    seq2 = seq[:indices[0]+k] + seq[indices[-1]-k:]
    if len(seq2)>len(seq):
        seq2 = seq
    return seq2

def get_modified_seq_alpha(seq,lig, cutoff_distance = 4.0):

    # hash = f"{generate_hashid(seq)}_{generate_hashid(lig)}"
    # path = f"/data/istiaq/work/projects/dti/NEWTON_outputs/def_clos_fur_bind_out/{hash}/{hash}_complex.pdb"

    # path = * provide path to the 3D complex for $seq$ and $lig$ generated by AlphaFold3 *
    if not os.path.isfile(path):
        print("NOT FOUND alpha mod")
        return seq
    print("Found alpha MOD")
    u = mda.Universe(path)
    ligand = u.select_atoms("resname LIG")
    binding_site_residues = u.select_atoms(f"protein and around {cutoff_distance} group ligand", ligand=ligand)
    residues = {(res.resname, res.resid) for res in binding_site_residues.residues}
    residues = sorted(residues, key=lambda x:x[1])
    ress = "".join([three_to_one[x[0]] for x in residues])
    indices = [y-1 for x,y in residues]

    # seq2 = seq[:indices[0]] + seq[indices[-1]:]
    # seq2 = "".join([seq[i] for i in range(len(seq)) if i not in indices])

    percentage = 0.0
    k = int(((indices[-1]-indices[0])*percentage)//2)

    seq2 = seq[:indices[0]+k] + seq[indices[-1]-k:]
    if len(seq2)>len(seq):
        seq2 = seq
    return seq2