import torch,sys,hydra
from torch.utils.data import Dataset, DataLoader
import pytorch_lightning as pl
from utils import utils
import numpy as np 
from scipy.spatial.distance import cdist
from matplotlib import pyplot as plt
import pickle
# pytorch datalaoder
import os
from collections import Counter
class MyDataset(Dataset):
    def __init__(self, DTI, test=False):
        self.test = test
        self.DTI = DTI
        self.device = "cpu"
        self.prot_featurizer = hydra.utils.instantiate(  {"_target_": "module.featurizer.prot_featurizer.esm_featurizer.ESMFEATURE"}, self.device, _recursive_=False)
        self.drug_featurizer = hydra.utils.instantiate(  {"_target_": "module.featurizer.drug_featurizer.chembert_featurizer.CHEMFEATURE"}, self.device, _recursive_=False)
        self.residue_cut_count = 0

    def __getitem__(self, index):
        y = self.DTI.iloc[index]['label'] # label
        smile = self.DTI.iloc[index]['SMILES'] # drug
        seq = self.DTI.iloc[index]['SEQ'] # protein
        if False:
            #  saved drug features can be loaded here
            x1 = x1
        else:
            print("Featuring drug")
            x1 = self.drug_featurizer.get_representations([smile])[0]

        
        if self.test:
            seq = seq
            percent = 10
            # seq = get_modified_seq(seq,smile,percent)
            # seq = get_modified_seq_alpha(seq,smile,percent)
            # seq = get_3_prime(seq,percent)
        
        if False:
            # saved protein features can be loaded here
            x2 = x2
        else:
            print("Featuring protein")
            # generate feature
            x2 = self.prot_featurizer.get_representations([seq])[0]
        pdb_id = ""
        # for x in  [x1,x2,y, "DRUGID", "PROTID", smile, seq, pdb_id]:
        #     print(type(x), x)
        # exit(0)
        return torch.tensor(x1).float(), torch.tensor(x2).float(), torch.tensor(y).float(), "DRUGID", "PROTID", smile, seq, pdb_id
        # drug_feat,prot_feat,label,drugID,protID,smile,seq,pdb
    def __len__(self):
        return len(self.DTI)


class UNIDataModule(pl.LightningDataModule):
    def __init__(self,config,dataset,dm_cfg):
        super().__init__()
        self.train_ind = dataset['train']
        self.val_ind = dataset['val']
        self.test_ind = dataset['test']    
        self.batch_size = dm_cfg['batch_size']
        self.num_workers = dm_cfg['num_workers']
        self.config = config
    
    def setup(self, stage):
        print("Number of samples in training",len(self.train_ind))
        print(f'Number of samples in test: {len(self.test_ind)}')
        self.train_dataset = MyDataset(self.train_ind)
        self.val_dataset = MyDataset(self.val_ind)
        self.test_dataset = MyDataset(self.test_ind, test=True)

    def train_dataloader(self):
        # REQUIRED
        return DataLoader(self.train_dataset, batch_size=self.batch_size , shuffle=True, num_workers=self.num_workers,
                          pin_memory=True, drop_last=True)

    def val_dataloader(self):
        # OPTIONAL
        return DataLoader(self.val_dataset, batch_size=self.batch_size, shuffle=False, num_workers=self.num_workers,
                          pin_memory=True, drop_last=False)

    def test_dataloader(self):
        # OPTIONAL
        
        loader1 = DataLoader(self.test_dataset, batch_size=self.batch_size, shuffle=False, num_workers=self.num_workers,
                         pin_memory=True, drop_last=False)
        return loader1  #[laoder1,laoder2]

import MDAnalysis as mda, os
from utils.utils import generate_hashid
three_to_one = {
    "ALA": "A", "ARG": "R", "ASN": "N", "ASP": "D", "CYS": "C",
    "GLU": "E", "GLN": "Q", "GLY": "G", "HIS": "H", "ILE": "I",
    "LEU": "L", "LYS": "K", "MET": "M", "PHE": "F", "PRO": "P",
    "SER": "S", "THR": "T", "TRP": "W", "TYR": "Y", "VAL": "V"
}

import random 

def get_3_prime(seq,percent):
    n = len(seq)
    percent = percent/100
    return seq[:int(n*percent)]

def get_5_prime(seq):
    n = len(seq)
    percent = .9
    return seq[int(n*percent):]

def get_modified_seq(seq,lig,percent,cutoff_distance = 4.0):

    # provide path to the 3D complex for $seq$ and $lig$ generated by DiffDock

    if not os.path.isfile(path):
        print("NOT FOUND2,",hash)
        return seq
    u = mda.Universe(path)
    ligand = u.select_atoms("resname UNL")
    binding_site_residues = u.select_atoms(f"protein and around {cutoff_distance} group ligand", ligand=ligand)
    residues = {(res.resname, res.resid) for res in binding_site_residues.residues}
    residues = sorted(residues, key=lambda x:x[1])
    ress = "".join([three_to_one[x[0]] for x in residues])
    indices = [y-1 for x,y in residues]

    ########### wholel part REPLACE with negative site #########################    
    # lighash = generate_hashid(lig)
    # if lighash in neg_binding_sites:
    #     neg = random.choice(neg_binding_sites[lighash])
    # else:
    #     neg = ""
    #     print("#$-$#")
    # seq2 = seq[:indices[0]] + neg + seq[indices[-1]:]
    ########### wholel part REPLACE with negative site #########################   

    ########### wholel part REPLACE with POSITIVE site #########################    
    # lighash = generate_hashid(lig)
    # if lighash in pos_binding_sites:
    #     pos = random.choice(pos_binding_sites[lighash])
    # else:
    #     pos = ""
    #     print("#$-$#")
    # seq2 = seq[:indices[0]] + pos + seq[indices[-1]:]
    ########### wholel part REPLACE with POSITIVE site #########################  
      

    ########### wholel part/ residue delete #########################    
    # seq2 = seq[:indices[0]] + seq[indices[-1]:]
    # seq2 = "".join([seq[i] for i in range(len(seq)) if i not in indices])
    ########### wholel part delete #########################    

    ########### percent delete #########################
    percentage = percent/100
    k = int(((indices[-1]-indices[0])*percentage)//2)
    seq2 = seq[:indices[0]+k] + seq[indices[-1]-k:]
    ########### percent delete #########################
    print("LEN ", len(seq2))
    # seq2 = seq
    if len(seq2)>len(seq):
        seq2 = seq
    return seq2


    
def get_modified_seq_alpha(seq,lig,percent, cutoff_distance = 4.0):
    # provide path to the 3D complex for $seq$ and $lig$ generated by AlphaFold3

    if not os.path.isfile(path):
        print("NOT FOUND,",hash)
        return seq
    u = mda.Universe(path)
    ligand = u.select_atoms("resname LIG")
    binding_site_residues = u.select_atoms(f"protein and around {cutoff_distance} group ligand", ligand=ligand)
    residues = {(res.resname, res.resid) for res in binding_site_residues.residues}
    residues = sorted(residues, key=lambda x:x[1])
    ress = "".join([three_to_one[x[0]] for x in residues])
    indices = [y-1 for x,y in residues]

    ########### wholel part REPLACE with negative site #########################    
    # lighash = generate_hashid(lig)
    # if lighash in neg_binding_sites:
    #     neg = random.choice(neg_binding_sites[lighash])
    # else:
    #     neg = ""
    #     print("#$-$#")
    # seq2 = seq[:indices[0]] + neg + seq[indices[-1]:]
    ########### wholel part REPLACE with negative site #########################   


    ########### wholel part REPLACE with POSITIVE site #########################    
    # lighash = generate_hashid(lig)
    # if lighash in pos_binding_sites:
    #     pos = random.choice(pos_binding_sites[lighash])
    # else:
    #     pos = ""
    #     print("#$-$#")
    # seq2 = seq[:indices[0]] + pos + seq[indices[-1]:]
    ########### wholel part REPLACE with POSITIVE site #########################  
      

    ########### wholel part/ residue delete #########################    
    # seq2 = seq[:indices[0]] + seq[indices[-1]:]
    # seq2 = "".join([seq[i] for i in range(len(seq)) if i not in indices])
    ########### wholel part delete #########################    


    ########### percent keep from both side of binding site #########################
    percentage = percent/100
    k = int(((indices[-1]-indices[0])*percentage)//2)
    seq2 = seq[:indices[0]+k] + seq[indices[-1]-k:]
    print("LEN ", len(seq2))
    ########### percent delete #########################
    if len(seq2)>len(seq):
        seq2 = seq
    return seq2

